modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="tfmg_oil_replacer"
version="1.0.0"
displayName="TFMG Oil Replacer"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="TimGe, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tfmg_oil_replacer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



